name: stt-opensource

services:
  stt-api:
    build: .
    ports:
      - "8080:8000"
    env_file: .env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
